# Form implementation generated from reading ui file 'prioritysieve/ui/known_morphs_exporter_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KnownMorphsExporterDialog(object):
    def setupUi(self, KnownMorphsExporterDialog):
        KnownMorphsExporterDialog.setObjectName("KnownMorphsExporterDialog")
        KnownMorphsExporterDialog.resize(523, 369)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(KnownMorphsExporterDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=KnownMorphsExporterDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectOutputPushButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.selectOutputPushButton.setObjectName("selectOutputPushButton")
        self.horizontalLayout.addWidget(self.selectOutputPushButton)
        self.outputLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout.addWidget(self.outputLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(parent=KnownMorphsExporterDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.includeReadingCheckBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.includeReadingCheckBox.setChecked(True)
        self.includeReadingCheckBox.setObjectName("includeReadingCheckBox")
        self.verticalLayout.addWidget(self.includeReadingCheckBox)
        self.includeReviewedOnlyCheckBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.includeReviewedOnlyCheckBox.setChecked(True)
        self.includeReviewedOnlyCheckBox.setObjectName("includeReviewedOnlyCheckBox")
        self.verticalLayout.addWidget(self.includeReviewedOnlyCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=KnownMorphsExporterDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addOccurrencesColumnCheckBox = QtWidgets.QCheckBox(parent=self.groupBox_3)
        self.addOccurrencesColumnCheckBox.setObjectName("addOccurrencesColumnCheckBox")
        self.verticalLayout_3.addWidget(self.addOccurrencesColumnCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.exportKnownMorphsPushButton = QtWidgets.QPushButton(parent=KnownMorphsExporterDialog)
        self.exportKnownMorphsPushButton.setObjectName("exportKnownMorphsPushButton")
        self.horizontalLayout_3.addWidget(self.exportKnownMorphsPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(KnownMorphsExporterDialog)
        QtCore.QMetaObject.connectSlotsByName(KnownMorphsExporterDialog)

    def retranslateUi(self, KnownMorphsExporterDialog):
        _translate = QtCore.QCoreApplication.translate
        KnownMorphsExporterDialog.setWindowTitle(_translate("KnownMorphsExporterDialog", "Known Entries Exporter"))
        self.groupBox_4.setTitle(_translate("KnownMorphsExporterDialog", "File Destination"))
        self.selectOutputPushButton.setText(_translate("KnownMorphsExporterDialog", "Select Output Directory"))
        self.groupBox.setTitle(_translate("KnownMorphsExporterDialog", "Included Columns"))
        self.includeReadingCheckBox.setText(_translate("KnownMorphsExporterDialog", "Include reading column"))
        self.includeReviewedOnlyCheckBox.setText(_translate("KnownMorphsExporterDialog", "Reviewed entries only"))
        self.groupBox_3.setTitle(_translate("KnownMorphsExporterDialog", "Extra"))
        self.addOccurrencesColumnCheckBox.setText(_translate("KnownMorphsExporterDialog", "Add occurrences column"))
        self.exportKnownMorphsPushButton.setText(_translate("KnownMorphsExporterDialog", "Export Known Entries"))
