# Form implementation generated from reading ui file 'prioritysieve/ui/known_entries_exporter_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_KnownEntriesExporterDialog(object):
    def setupUi(self, KnownEntriesExporterDialog):
        KnownEntriesExporterDialog.setObjectName("KnownEntriesExporterDialog")
        KnownEntriesExporterDialog.resize(523, 369)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(KnownEntriesExporterDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=KnownEntriesExporterDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectOutputPushButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.selectOutputPushButton.setObjectName("selectOutputPushButton")
        self.horizontalLayout.addWidget(self.selectOutputPushButton)
        self.outputLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout.addWidget(self.outputLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(parent=KnownEntriesExporterDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.includeReadingCheckBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.includeReadingCheckBox.setChecked(True)
        self.includeReadingCheckBox.setObjectName("includeReadingCheckBox")
        self.verticalLayout.addWidget(self.includeReadingCheckBox)
        self.includeReviewedOnlyCheckBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.includeReviewedOnlyCheckBox.setChecked(True)
        self.includeReviewedOnlyCheckBox.setObjectName("includeReviewedOnlyCheckBox")
        self.verticalLayout.addWidget(self.includeReviewedOnlyCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=KnownEntriesExporterDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addOccurrencesColumnCheckBox = QtWidgets.QCheckBox(parent=self.groupBox_3)
        self.addOccurrencesColumnCheckBox.setObjectName("addOccurrencesColumnCheckBox")
        self.verticalLayout_3.addWidget(self.addOccurrencesColumnCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.exportKnownEntriesPushButton = QtWidgets.QPushButton(parent=KnownEntriesExporterDialog)
        self.exportKnownEntriesPushButton.setObjectName("exportKnownEntriesPushButton")
        self.horizontalLayout_3.addWidget(self.exportKnownEntriesPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(KnownEntriesExporterDialog)
        QtCore.QMetaObject.connectSlotsByName(KnownEntriesExporterDialog)

    def retranslateUi(self, KnownEntriesExporterDialog):
        _translate = QtCore.QCoreApplication.translate
        KnownEntriesExporterDialog.setWindowTitle(_translate("KnownEntriesExporterDialog", "Known Entries Exporter"))
        self.groupBox_4.setTitle(_translate("KnownEntriesExporterDialog", "File Destination"))
        self.selectOutputPushButton.setText(_translate("KnownEntriesExporterDialog", "Select Output Directory"))
        self.groupBox.setTitle(_translate("KnownEntriesExporterDialog", "Included Columns"))
        self.includeReadingCheckBox.setText(_translate("KnownEntriesExporterDialog", "Include reading column"))
        self.includeReviewedOnlyCheckBox.setText(_translate("KnownEntriesExporterDialog", "Reviewed entries only"))
        self.groupBox_3.setTitle(_translate("KnownEntriesExporterDialog", "Extra"))
        self.addOccurrencesColumnCheckBox.setText(_translate("KnownEntriesExporterDialog", "Add occurrences column"))
        self.exportKnownEntriesPushButton.setText(_translate("KnownEntriesExporterDialog", "Export Known Entries"))
